displayName=Clan Home World Hopper
author=Proddy
description=A plugin to add a "Hop-to" option to the clan home world.
tags=clan,home,world,hop,hopper
version=1.0
plugins=org.zhbot.clan_home_world_hopper.ClanHomeWorldHopperPlugin
build=standard